name: Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt install -y meson libgtest-dev pkg-config 
    - name: Run tests with ASan
      run: |
        meson setup builddir -Db_sanitize=address
        ninja -C builddir test